# This is a basic workflow to help you get started with Actions

name: CI-dev-PR

# https://docs.github.com/en/actions/using-jobs/using-jobs-in-a-workflow

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "dev" branch
  pull_request:
    branches: ["dev"]

  # Allows you to run this workflow manually from the Actions tab, only possible if this file is in the default branch (aka master)
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"

  static-analysis:
    name: Static Analysis

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # - name: Install dependencies
      #   run: |
      #     python -m pip install --upgrade pip
      #     pip install flake8 pytest

      # - name: Lint with flake8
      #   run: |
      #     flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
      #     flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

  build:
    name: Build
    needs: [static-analysis]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Build package
        run: python -m build

  tests:
    name: Tests
    needs: [static-analysis, build]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          echo "pip install requirements.txt"

      - name: Run tests
        run: echo "python -m  pytest"

  # # This workflow contains a single job called "build"
  # build:
  #   name: Build

  #   # The type of runner that the job will run on
  #   runs-on: ubuntu-latest

  #   # Steps represent a sequence of tasks that will be executed as part of the job
  #   steps:
  #     # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
  #     - uses: actions/checkout@v4

  #     # # Runs a single command using the runners shell
  #     # - name: Run a one-line script
  #     #   run: echo Hello, world!

  #     # Runs a set of commands using the runners shell
  #     - name: Run a multi-line script
  #       run: |
  #         echo Add other actions to build,
  #         echo test, and deploy your project.

  update-status:
    name: Update Commit Status
    needs: [static-analysis, build, tests]
    runs-on: ubuntu-latest
    steps:
      - name: All previous jobs succeeded
        run: echo "All jobs succeeded!"

      - name: Update commit status
        run: |
          # Use the GitHub Status API to update the commit status
          curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            -d '{"state": "success", "description": "All dev checks passed", "context": "ci/all-checks-dev"}' \
            https://api.github.com/repos/OWNER/REPO/commits/REF/status
