# This is a basic workflow to help you get started with Actions

name: CI-master-PR

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  # push:
  #   branches: [ "master" ]
  pull_request:
    branches: ["master"]

  # Allows you to run this workflow manually from the Actions tab, only possible if this file is in the default branch (aka master)
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  version-analysis:
    name: Version Analysis

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Checks if different version than master
        run: ./.github/scripts/compare-version-master.sh

      - name: Checks if version matches current Paris date
        run: ./.github/scripts/compare-version-date.h

  static-analysis:
    name: Static Analysis
    needs: version-analysis

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # - name: Install dependencies
      #   run: |
      #     python -m pip install --upgrade pip
      #     pip install flake8 pytest

      # - name: Lint with flake8
      #   run: |
      #     flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
      #     flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

  build:
    name: Build
    needs: [version-analysis, static-analysis]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Build package
        run: python -m build

  tests:
    name: Tests
    needs: [version-analysis, static-analysis, build]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          echo "pip install requirements.txt"

      - name: Run tests
        run: echo "python -m pytest"

  update-status:
    name: Update Commit Status
    needs: [version-analysis, static-analysis, build, tests]
    runs-on: ubuntu-latest
    steps:
      - name: All previous jobs succeeded
        run: echo "All jobs succeeded!"

      - name: Update commit status
        run: |
          # Extract the commit SHA from the GITHUB_SHA environment variable
          COMMIT_SHA=${GITHUB_SHA}

          # Use the GitHub Status API to update the commit status
          curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${GITHUB_TOKEN}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            -d '{"state": "success", "description": "All master checks passed", "context": "ci/all-checks-master"}' \
            https://api.github.com/repos/OWNER/REPO/commits/REF/status
