name: CI-releases

# Controls when the workflow will run
on:
  # Triggers the workflow on pull request events but only for the "master" branch
  push:
    branches:
      - 'releases/**'

  # Allows you to run this workflow manually from the Actions tab, only possible if this file is in the default branch (aka master)
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # Runs the static analysis of codebase
  static-analysis:
    name: Static Analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      # - name: Install dependencies
      #   run: |
      #     python -m pip install --upgrade pip
      #     pip install flake8 pytest

      # - name: Lint with flake8
      #   run: |
      #     flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
      #     flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

  # Runs unit tests
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          echo "pip install requirements.txt"

      - name: Run tests
        run: echo "python -m pytest"

  # Runs the integration tests (only on the master branch)
  integration-tests:
    name: Integration Tests
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          echo "pip install requirements.txt"

      - name: Run tests
        run: echo "python ./tests/integration_tests.py"